// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orm

import (
	"database/sql"
)

type Channel struct {
	ID       int64
	Hash     int64
	Username string
	StoredAt int64
}

type Fetcher struct {
	ID      int64
	ApiID   sql.NullInt64
	ApiHash sql.NullString
}

type Sub struct {
	Chat    int64
	Channel int64
}
