// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package orm

import (
	"context"
)

const changeChannelUsername = `-- name: ChangeChannelUsername :exec
UPDATE channels
SET username = $2
WHERE id = $1
`

type ChangeChannelUsernameParams struct {
	ID       int64
	Username string
}

func (q *Queries) ChangeChannelUsername(ctx context.Context, arg ChangeChannelUsernameParams) error {
	_, err := q.db.ExecContext(ctx, changeChannelUsername, arg.ID, arg.Username)
	return err
}

const getUsernamesOfGroupSubs = `-- name: GetUsernamesOfGroupSubs :many
SELECT channels.username FROM channels
JOIN subs ON channels.id = subs.channel
WHERE subs.chat = $1
`

func (q *Queries) GetUsernamesOfGroupSubs(ctx context.Context, chat int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsernamesOfGroupSubs, chat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
