// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fetchers.sql

package orm

import (
	"context"
)

const checkFetcher = `-- name: CheckFetcher :one
SELECT COUNT(1)
FROM fetchers
WHERE id = $1
`

func (q *Queries) CheckFetcher(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkFetcher, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
