// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subs.sql

package orm

import (
	"context"
)

const checkSub = `-- name: CheckSub :one
SELECT COUNT(1) FROM subs
WHERE chat = $1 AND channel = $2
`

type CheckSubParams struct {
	Chat    int64
	Channel int64
}

func (q *Queries) CheckSub(ctx context.Context, arg CheckSubParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSub, arg.Chat, arg.Channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubsOfChannel = `-- name: CountSubsOfChannel :one
SELECT COUNT(*) FROM subs
WHERE channel = $1
`

func (q *Queries) CountSubsOfChannel(ctx context.Context, channel int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubsOfChannel, channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubsOfChannel = `-- name: GetSubsOfChannel :many
SELECT chat, thread FROM subs
WHERE channel = $1
`

type GetSubsOfChannelRow struct {
	Chat   int64
	Thread int64
}

func (q *Queries) GetSubsOfChannel(ctx context.Context, channel int64) ([]GetSubsOfChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubsOfChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubsOfChannelRow
	for rows.Next() {
		var i GetSubsOfChannelRow
		if err := rows.Scan(&i.Chat, &i.Thread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupIDChanged = `-- name: GroupIDChanged :exec
UPDATE subs SET chat = $2
WHERE chat = $1
`

type GroupIDChangedParams struct {
	Chat   int64
	Chat_2 int64
}

func (q *Queries) GroupIDChanged(ctx context.Context, arg GroupIDChangedParams) error {
	_, err := q.db.ExecContext(ctx, groupIDChanged, arg.Chat, arg.Chat_2)
	return err
}

const subscribe = `-- name: Subscribe :one
INSERT INTO subs(chat, channel, thread)
VALUES ($1, $2, $3)
RETURNING chat, channel, thread
`

type SubscribeParams struct {
	Chat    int64
	Channel int64
	Thread  int64
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) (Sub, error) {
	row := q.db.QueryRowContext(ctx, subscribe, arg.Chat, arg.Channel, arg.Thread)
	var i Sub
	err := row.Scan(&i.Chat, &i.Channel, &i.Thread)
	return i, err
}

const unSubscribe = `-- name: UnSubscribe :exec
DELETE FROM subs
WHERE chat = $1 AND channel = $2
`

type UnSubscribeParams struct {
	Chat    int64
	Channel int64
}

func (q *Queries) UnSubscribe(ctx context.Context, arg UnSubscribeParams) error {
	_, err := q.db.ExecContext(ctx, unSubscribe, arg.Chat, arg.Channel)
	return err
}
