// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subs.sql

package orm

import (
	"context"
)

const getSubsOfChannel = `-- name: GetSubsOfChannel :many
SELECT chat FROM subs
WHERE channel = $1
`

func (q *Queries) GetSubsOfChannel(ctx context.Context, channel int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getSubsOfChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var chat int64
		if err := rows.Scan(&chat); err != nil {
			return nil, err
		}
		items = append(items, chat)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
